# Generated by Django 4.1.5 on 2023-02-06 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('inventory', models.CharField(choices=[('A', 'in stock'), ('B', 'out of stock')], default='A', max_length=1)),
                ('mini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mini')),
            ],
        ),
    ]
