# Generated by Django 4.1.5 on 2023-02-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(verbose_name='Last Updated'),
        ),
    ]
